export const INITIAL_CARDS = [
  {
    id: 'mock-card-1-v1',
    cardId: 'mock-card-1',
    knowledgePointId: 'mock-kp-1',
    version: 1,
    title: '项目与运营有什么区别？',
    conclusion: '项目是临时性的，运营是持续性的。',
    explanation: '项目有明确的开始和结束，运营持续产生重复性结果。',
    example: '实施一次系统升级是项目，日常客服支持是运营。',
    recallPrompt: '请回忆：项目和运营最关键的区别是什么？',
    referenceAnswer: '项目是临时性工作，运营是持续性工作。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 1 / Foundations'
  },
  {
    id: 'mock-card-2-v1',
    cardId: 'mock-card-2',
    knowledgePointId: 'mock-kp-2',
    version: 1,
    title: '项目生命周期是什么？',
    conclusion: '项目生命周期是项目从开始到结束所经历的一组阶段。',
    explanation: '不同项目的阶段名称可能不同，但都需要明确阶段目标、交付物和决策点。',
    example: '一个产品项目可以拆分为启动、规划、执行、交付和收尾。',
    recallPrompt: '项目生命周期阶段需要明确哪些内容？',
    referenceAnswer: '阶段目标、交付物和决策点。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 2 / Life cycle'
  },
  {
    id: 'mock-card-3-v1',
    cardId: 'mock-card-3',
    knowledgePointId: 'mock-kp-3',
    version: 1,
    title: '相关方为什么重要？',
    conclusion: '相关方的态度和影响力会影响项目结果。',
    explanation: '项目团队需要识别相关方，理解其期望，并持续沟通和参与管理。',
    example: '关键用户没有参与评审，可能导致交付物无法被接受。',
    recallPrompt: '管理相关方的第一步是什么？',
    referenceAnswer: '识别相关方并理解其影响力、期望和参与方式。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 3 / Stakeholders'
  },
  {
    id: 'mock-card-4-v1',
    cardId: 'mock-card-4',
    knowledgePointId: 'mock-kp-4',
    version: 1,
    title: '项目最核心的特征是什么？',
    conclusion: '项目是为创造独特成果而开展的临时性工作。',
    explanation: '项目有明确的开始和结束，并会产生独特的产品、服务或结果。',
    example: '建设一座办公楼是项目，日常保洁工作属于运营。',
    recallPrompt: '请回忆：项目与日常运营的两个关键区别是什么？',
    referenceAnswer: '项目是临时性的，并产生独特成果。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 1 / Foundations'
  },
  {
    id: 'mock-card-5-v1',
    cardId: 'mock-card-5',
    knowledgePointId: 'mock-kp-5',
    version: 1,
    title: '项目集和项目组合有什么区别？',
    conclusion: '项目集关注相互关联项目的协同管理，项目组合关注战略目标。',
    explanation: '项目集中的项目通常具有关联性，统一管理可以获得单独管理无法获得的收益。',
    example: '多个互相依赖的数字化项目可以组成一个项目集。',
    recallPrompt: '请回忆：项目集和项目组合分别解决什么问题？',
    referenceAnswer: '项目集解决关联项目的协同与收益，项目组合解决战略优先级。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 1 / Foundations'
  },
  {
    id: 'mock-card-6-v1',
    cardId: 'mock-card-6',
    knowledgePointId: 'mock-kp-6',
    version: 1,
    title: '项目经理的核心职责是什么？',
    conclusion: '项目经理负责协调资源，推动项目在约束条件下交付成果。',
    explanation: '项目经理需要促进沟通、管理风险和问题，并帮助团队聚焦项目目标。',
    example: '当多个团队争用同一资源时，项目经理需要协调优先级。',
    recallPrompt: '项目经理不只是“派任务”，还需要协调什么？',
    referenceAnswer: '协调资源、沟通相关方、处理风险和推动目标达成。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 1 / Foundations'
  },
  {
    id: 'mock-card-7-v1',
    cardId: 'mock-card-7',
    knowledgePointId: 'mock-kp-7',
    version: 1,
    title: '项目治理解决什么问题？',
    conclusion: '项目治理规定决策、监督和问责的机制。',
    explanation: '治理明确谁可以做决定、如何升级问题，以及项目如何与组织目标保持一致。',
    example: '重大预算变更需要提交指导委员会审批，就是治理机制的一部分。',
    recallPrompt: '项目治理通常明确哪三类内容？',
    referenceAnswer: '决策权限、监督机制和问责方式。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 1 / Foundations'
  },
  {
    id: 'mock-card-8-v1',
    cardId: 'mock-card-8',
    knowledgePointId: 'mock-kp-8',
    version: 1,
    title: '什么是项目裁剪？',
    conclusion: '项目裁剪是根据项目环境选择和调整管理方法。',
    explanation: '不同项目的规模、复杂度、行业和风险不同，不应机械套用同一套流程。',
    example: '小型内部项目可以使用轻量审批，大型监管项目需要更完整的记录。',
    recallPrompt: '项目裁剪是减少所有流程，还是选择适合项目的流程？',
    referenceAnswer: '选择并调整适合当前项目环境的流程、方法和工件。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 1 / Foundations'
  },
  {
    id: 'mock-card-9-v1',
    cardId: 'mock-card-9',
    knowledgePointId: 'mock-kp-9',
    version: 1,
    title: '风险和问题有什么区别？',
    conclusion: '风险是可能发生的事件，问题是已经发生的事件。',
    explanation: '风险需要分析概率和影响并提前应对，问题需要立即处理和跟踪。',
    example: '供应商可能延期是风险，供应商已经延期是问题。',
    recallPrompt: '面对一个尚未发生但可能影响项目的事件，应先把它归为什么？',
    referenceAnswer: '风险。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 1 / Foundations'
  },
  {
    id: 'mock-card-10-v1',
    cardId: 'mock-card-10',
    knowledgePointId: 'mock-kp-10',
    version: 1,
    title: '项目章程的作用是什么？',
    conclusion: '项目章程正式授权项目，并赋予项目经理使用组织资源的权限。',
    explanation: '章程通常描述项目目标、主要交付物、关键相关方和高层级约束。',
    example: '项目章程批准后，项目团队才有正式依据开展规划工作。',
    recallPrompt: '项目章程最重要的两个作用是什么？',
    referenceAnswer: '正式启动项目，并授权项目经理使用资源。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 1 / Foundations'
  },
  {
    id: 'mock-card-11-v1',
    cardId: 'mock-card-11',
    knowledgePointId: 'mock-kp-11',
    version: 1,
    title: '项目收益管理关注什么？',
    conclusion: '收益管理关注项目成果是否带来预期价值。',
    explanation: '项目交付物完成不等于收益已经实现，还需要明确收益指标和责任人。',
    example: '上线系统只是交付物，系统带来的处理效率提升才是收益。',
    recallPrompt: '交付物和收益之间是什么关系？',
    referenceAnswer: '交付物是成果，收益是成果带来的可衡量价值。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 1 / Foundations'
  },
  {
    id: 'mock-card-12-v1',
    cardId: 'mock-card-12',
    knowledgePointId: 'mock-kp-12',
    version: 1,
    title: 'PMO 可以提供什么支持？',
    conclusion: 'PMO 可以提供标准、方法、资源协调和项目支持。',
    explanation: '不同 PMO 的授权程度不同，有的提供支持，有的负责监督或直接管理项目。',
    example: 'PMO 统一模板和培训，可以减少不同项目重复设计流程的成本。',
    recallPrompt: 'PMO 的职责是否在所有组织中完全相同？',
    referenceAnswer: '不相同，取决于组织对 PMO 的授权和定位。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 1 / Foundations'
  },
  {
    id: 'mock-card-13-v1',
    cardId: 'mock-card-13',
    knowledgePointId: 'mock-kp-13',
    version: 1,
    title: '项目约束之间如何相互影响？',
    conclusion: '范围、进度、成本、质量、资源和风险等约束需要综合平衡。',
    explanation: '改变一个约束往往会影响其他约束，不能只看单一指标。',
    example: '要求提前交付，可能需要增加资源或减少范围。',
    recallPrompt: '为什么不能只要求项目“更快”而不调整其他内容？',
    referenceAnswer: '因为进度变化通常会影响成本、资源、范围或质量。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 1 / Foundations'
  },
  {
    id: 'mock-card-14-v1',
    cardId: 'mock-card-14',
    knowledgePointId: 'mock-kp-14',
    version: 1,
    title: '项目成功应该如何判断？',
    conclusion: '项目成功需要同时考虑交付结果、相关方满意度和预期价值。',
    explanation: '按时按预算交付不一定代表成功，还要看成果是否解决了业务问题。',
    example: '系统按期上线但无人使用，不能简单判定项目成功。',
    recallPrompt: '项目成功不能只看哪三个传统指标？',
    referenceAnswer: '不能只看范围、进度和成本，还要看价值和满意度。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 1 / Foundations'
  },
  {
    id: 'mock-card-15-v1',
    cardId: 'mock-card-15',
    knowledgePointId: 'mock-kp-15',
    version: 1,
    title: '项目中的职业道德为什么重要？',
    conclusion: '诚信、责任、公平和尊重有助于建立信任并支持正确决策。',
    explanation: '项目管理中的信息、资源和决策会影响多个群体，需要避免隐瞒和利益冲突。',
    example: '发现估算存在重大偏差时，应及时披露而不是故意隐瞒。',
    recallPrompt: '面对利益冲突时，项目人员首先应保持什么原则？',
    referenceAnswer: '诚实透明，识别并妥善披露利益冲突。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 1 / Foundations'
  },
  {
    id: 'mock-card-16-v1',
    cardId: 'mock-card-16',
    knowledgePointId: 'mock-kp-16',
    version: 1,
    title: '项目生命周期阶段有什么作用？',
    conclusion: '生命周期阶段帮助团队组织工作，并在关键点进行评审和决策。',
    explanation: '阶段可以按项目类型划分，每个阶段通常有目标、交付物和结束条件。',
    example: '在设计阶段结束时评审方案，可以减少后续返工。',
    recallPrompt: '一个生命周期阶段通常需要明确哪些内容？',
    referenceAnswer: '阶段目标、主要交付物和决策点。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 2 / Predictive'
  },
  {
    id: 'mock-card-17-v1',
    cardId: 'mock-card-17',
    knowledgePointId: 'mock-kp-17',
    version: 1,
    title: '预测型项目管理的特点是什么？',
    conclusion: '预测型方法通常在早期详细规划范围，再按计划执行。',
    explanation: '它适合需求相对稳定、变更成本较高或需要阶段性审批的项目。',
    example: '基础设施建设通常需要在施工前完成大量设计和审批。',
    recallPrompt: '预测型方法更适合什么样的需求环境？',
    referenceAnswer: '需求相对稳定、可以较早明确范围的环境。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 2 / Predictive'
  },
  {
    id: 'mock-card-18-v1',
    cardId: 'mock-card-18',
    knowledgePointId: 'mock-kp-18',
    version: 1,
    title: '什么是阶段关口？',
    conclusion: '阶段关口是在阶段结束时评审成果并决定是否继续。',
    explanation: '关口可以检查目标、风险、成本和交付物，为继续、调整或终止项目提供依据。',
    example: '产品原型评审未通过时，项目可能需要回到设计阶段。',
    recallPrompt: '阶段关口的核心不是汇报，而是做什么？',
    referenceAnswer: '基于阶段成果和信息做继续、调整或终止决策。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 2 / Predictive'
  },
  {
    id: 'mock-card-19-v1',
    cardId: 'mock-card-19',
    knowledgePointId: 'mock-kp-19',
    version: 1,
    title: 'WBS 的主要作用是什么？',
    conclusion: 'WBS 将项目范围分解为更易管理的工作包。',
    explanation: 'WBS 按可交付成果组织工作，而不是简单按人员或部门列任务。',
    example: '建设网站可以分解为需求、设计、开发、测试和上线等可交付成果。',
    recallPrompt: 'WBS 分解的重点是工作动作还是可交付成果？',
    referenceAnswer: '重点是可交付成果和组成它们的工作。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 2 / Predictive'
  },
  {
    id: 'mock-card-20-v1',
    cardId: 'mock-card-20',
    knowledgePointId: 'mock-kp-20',
    version: 1,
    title: '范围基准包含什么？',
    conclusion: '范围基准通常由范围说明书、WBS 和 WBS 词典组成。',
    explanation: '范围基准描述项目要交付什么以及工作如何分解和定义。',
    example: '未经批准的新增功能不能直接成为范围基准的一部分。',
    recallPrompt: '范围基准的三个典型组成部分是什么？',
    referenceAnswer: '范围说明书、WBS 和 WBS 词典。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 2 / Predictive'
  },
  {
    id: 'mock-card-21-v1',
    cardId: 'mock-card-21',
    knowledgePointId: 'mock-kp-21',
    version: 1,
    title: '进度基准的作用是什么？',
    conclusion: '进度基准是比较实际进展和计划进展的依据。',
    explanation: '它包含经批准的项目时间安排，变更需要经过正式控制。',
    example: '项目延期后不能直接覆盖原计划，否则无法分析偏差。',
    recallPrompt: '为什么要保留原来的进度基准？',
    referenceAnswer: '为了比较计划与实际，并分析进度偏差。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 2 / Predictive'
  },
  {
    id: 'mock-card-22-v1',
    cardId: 'mock-card-22',
    knowledgePointId: 'mock-kp-22',
    version: 1,
    title: '关键路径是什么？',
    conclusion: '关键路径是项目网络图中总工期最长的路径。',
    explanation: '关键路径决定项目最早完成时间，路径上的活动通常总浮动时间最少。',
    example: '关键路径上的一个活动延期，可能直接导致项目延期。',
    recallPrompt: '关键路径是活动数量最多的路径吗？',
    referenceAnswer: '不是，它是总工期最长的路径。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 2 / Predictive'
  },
  {
    id: 'mock-card-23-v1',
    cardId: 'mock-card-23',
    knowledgePointId: 'mock-kp-23',
    version: 1,
    title: '总浮动时间表示什么？',
    conclusion: '总浮动时间表示活动在不影响项目完成日期时可以延迟的时间。',
    explanation: '浮动时间帮助项目团队识别进度灵活性和需要重点关注的活动。',
    example: '总浮动时间为零的活动通常位于关键路径上。',
    recallPrompt: '总浮动时间为零意味着什么？',
    referenceAnswer: '该活动没有不影响项目完成日期的可用延迟时间。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 2 / Predictive'
  },
  {
    id: 'mock-card-24-v1',
    cardId: 'mock-card-24',
    knowledgePointId: 'mock-kp-24',
    version: 1,
    title: '成本基准的用途是什么？',
    conclusion: '成本基准是按时间分配的经批准项目预算。',
    explanation: '它用于比较实际成本和计划成本，并支持项目成本控制。',
    example: '单纯知道总预算，不能判断每个阶段是否超支。',
    recallPrompt: '成本基准与总预算的主要区别是什么？',
    referenceAnswer: '成本基准将经批准预算按时间分配，用于跟踪和比较。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 2 / Predictive'
  },
  {
    id: 'mock-card-25-v1',
    cardId: 'mock-card-25',
    knowledgePointId: 'mock-kp-25',
    version: 1,
    title: '估算应该什么时候更新？',
    conclusion: '获得更多信息或发生重大变化时，应重新评估估算。',
    explanation: '估算不是一次性承诺，随着项目知识增加，估算可以逐步变得更准确。',
    example: '完成原型验证后，开发工作量估算可能需要更新。',
    recallPrompt: '更新估算是否一定代表项目做得不好？',
    referenceAnswer: '不一定，估算应随着信息变化而持续完善。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 2 / Predictive'
  },
  {
    id: 'mock-card-26-v1',
    cardId: 'mock-card-26',
    knowledgePointId: 'mock-kp-26',
    version: 1,
    title: '质量保证和质量控制有什么区别？',
    conclusion: '质量保证关注过程，质量控制关注交付物和结果。',
    explanation: '质量保证通过改进过程预防问题，质量控制通过检查和测试发现问题。',
    example: '评审开发流程属于质量保证，测试功能缺陷属于质量控制。',
    recallPrompt: '测试一个交付物属于质量保证还是质量控制？',
    referenceAnswer: '质量控制。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 2 / Predictive'
  },
  {
    id: 'mock-card-27-v1',
    cardId: 'mock-card-27',
    knowledgePointId: 'mock-kp-27',
    version: 1,
    title: '变更控制的第一步是什么？',
    conclusion: '变更控制首先要记录并评估变更请求的影响。',
    explanation: '需要分析变更对范围、进度、成本、质量、资源和风险的影响，再做审批决定。',
    example: '客户提出新增功能时，不能直接安排开发而跳过影响分析。',
    recallPrompt: '为什么不能收到变更请求就马上执行？',
    referenceAnswer: '因为需要先评估对项目基准和其他约束的影响。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 2 / Predictive'
  },
  {
    id: 'mock-card-28-v1',
    cardId: 'mock-card-28',
    knowledgePointId: 'mock-kp-28',
    version: 1,
    title: '项目收尾需要确认什么？',
    conclusion: '收尾需要确认交付物验收、合同关闭、资料归档和经验总结。',
    explanation: '项目完成不只是停止工作，还要完成正式移交并释放资源。',
    example: '产品上线后，仍需要完成验收签字和运维交接。',
    recallPrompt: '项目收尾为什么不能只宣布“上线完成”？',
    referenceAnswer: '还需要完成验收、移交、归档、合同关闭和经验总结。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 2 / Predictive'
  },
  {
    id: 'mock-card-29-v1',
    cardId: 'mock-card-29',
    knowledgePointId: 'mock-kp-29',
    version: 1,
    title: '敏捷方法强调什么？',
    conclusion: '敏捷方法强调快速反馈、持续交付和适应变化。',
    explanation: '团队通过较短周期交付可验证成果，并根据反馈调整后续工作。',
    example: '先交付最小可用功能，再根据用户反馈安排下一轮改进。',
    recallPrompt: '敏捷团队为什么要缩短反馈周期？',
    referenceAnswer: '为了尽早发现问题并适应需求变化。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 3 / Agile'
  },
  {
    id: 'mock-card-30-v1',
    cardId: 'mock-card-30',
    knowledgePointId: 'mock-kp-30',
    version: 1,
    title: '迭代和增量分别强调什么？',
    conclusion: '迭代强调逐步改进，增量强调逐步增加可用功能。',
    explanation: '一次交付可以既是迭代又是增量，但两个概念关注点不同。',
    example: '先做出功能原型再不断优化是迭代，逐步增加支付和退款功能是增量。',
    recallPrompt: '迭代主要解决改进问题，增量主要解决什么问题？',
    referenceAnswer: '逐步增加可用的产品功能。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 3 / Agile'
  },
  {
    id: 'mock-card-31-v1',
    cardId: 'mock-card-31',
    knowledgePointId: 'mock-kp-31',
    version: 1,
    title: '产品待办列表是什么？',
    conclusion: '产品待办列表是按优先级排列的产品需求和工作集合。',
    explanation: '它是动态变化的，团队会根据价值、风险、反馈和约束不断调整顺序。',
    example: '用户登录、搜索和支付功能都可以作为待办项进行排序。',
    recallPrompt: '产品待办列表是一次性固定的吗？',
    referenceAnswer: '不是，它会随着学习和反馈持续更新。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 3 / Agile'
  },
  {
    id: 'mock-card-32-v1',
    cardId: 'mock-card-32',
    knowledgePointId: 'mock-kp-32',
    version: 1,
    title: '用户故事通常描述什么？',
    conclusion: '用户故事从用户角色、需求和价值角度描述功能。',
    explanation: '常见表达是“作为某类用户，我希望完成某件事，以便获得某种价值”。',
    example: '作为学生，我希望保存错题，以便之后集中复习。',
    recallPrompt: '用户故事中为什么要写清楚价值？',
    referenceAnswer: '帮助团队理解需求目的并判断优先级。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 3 / Agile'
  },
  {
    id: 'mock-card-33-v1',
    cardId: 'mock-card-33',
    knowledgePointId: 'mock-kp-33',
    version: 1,
    title: '验收标准的作用是什么？',
    conclusion: '验收标准定义需求被认为完成和可接受的条件。',
    explanation: '清晰的验收标准可以减少理解差异，并帮助团队验证交付结果。',
    example: '登录功能的验收标准可以包括错误密码提示和成功跳转。',
    recallPrompt: '验收标准主要帮助谁判断结果是否完成？',
    referenceAnswer: '团队和相关方共同判断交付结果是否满足需求。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 3 / Agile'
  },
  {
    id: 'mock-card-34-v1',
    cardId: 'mock-card-34',
    knowledgePointId: 'mock-kp-34',
    version: 1,
    title: '产品负责人通常负责什么？',
    conclusion: '产品负责人负责最大化产品价值并管理产品待办列表。',
    explanation: '产品负责人需要理解用户和业务目标，并对需求优先级做出决定。',
    example: '当两个功能争夺同一迭代资源时，产品负责人需要确定优先顺序。',
    recallPrompt: '产品负责人最核心的决策对象是什么？',
    referenceAnswer: '产品价值和产品待办列表的优先级。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 3 / Agile'
  },
  {
    id: 'mock-card-35-v1',
    cardId: 'mock-card-35',
    knowledgePointId: 'mock-kp-35',
    version: 1,
    title: '每日站会的目的是什么？',
    conclusion: '每日站会用于同步进展、识别障碍并协调当天工作。',
    explanation: '站会应简短聚焦团队协作，不应变成长时间的逐人汇报。',
    example: '团队发现测试环境不可用后，可以在站会上及时升级处理。',
    recallPrompt: '每日站会重点解决的是汇报还是协作？',
    referenceAnswer: '协作、同步和障碍识别。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 3 / Agile'
  },
  {
    id: 'mock-card-36-v1',
    cardId: 'mock-card-36',
    knowledgePointId: 'mock-kp-36',
    version: 1,
    title: '迭代评审的重点是什么？',
    conclusion: '迭代评审展示已完成成果，并收集相关方反馈。',
    explanation: '评审关注实际完成的产品增量，而不是只展示计划或汇报工作量。',
    example: '团队向用户演示可操作的新功能，并记录改进意见。',
    recallPrompt: '迭代评审应该展示计划还是可用成果？',
    referenceAnswer: '展示可用的成果并收集反馈。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 3 / Agile'
  },
  {
    id: 'mock-card-37-v1',
    cardId: 'mock-card-37',
    knowledgePointId: 'mock-kp-37',
    version: 1,
    title: '回顾会议关注什么？',
    conclusion: '回顾会议关注团队如何改进工作方式和协作过程。',
    explanation: '团队讨论做得好的地方、遇到的问题以及下一轮可以尝试的改进。',
    example: '团队决定在下个迭代中提前安排测试数据准备。',
    recallPrompt: '回顾会议主要评审产品成果还是工作过程？',
    referenceAnswer: '主要反思和改进工作过程与协作方式。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 3 / Agile'
  },
  {
    id: 'mock-card-38-v1',
    cardId: 'mock-card-38',
    knowledgePointId: 'mock-kp-38',
    version: 1,
    title: '看板中的 WIP 限制是什么？',
    conclusion: 'WIP 限制控制同时进行的工作数量，帮助减少拥堵。',
    explanation: '限制在制品可以让团队更早完成已有工作，而不是不断开启新工作。',
    example: '开发列最多同时处理三项任务，空出位置后再拉取新任务。',
    recallPrompt: 'WIP 限制的目的是真正减少工作，还是减少同时进行的工作？',
    referenceAnswer: '减少同时进行的工作并改善流动。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 3 / Agile'
  },
  {
    id: 'mock-card-39-v1',
    cardId: 'mock-card-39',
    knowledgePointId: 'mock-kp-39',
    version: 1,
    title: '混合型方法适合什么场景？',
    conclusion: '混合型方法结合预测型和敏捷型实践，适应不同部分的需求特征。',
    explanation: '项目可以对合规、采购等稳定部分使用预测型方法，对产品开发使用迭代方法。',
    example: '硬件按阶段审批，软件功能按短迭代开发，是一种混合方式。',
    recallPrompt: '混合型不是简单平均两种方法，而是根据什么进行组合？',
    referenceAnswer: '根据项目不同部分的需求、风险和约束进行组合。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 3 / Hybrid'
  },
  {
    id: 'mock-card-40-v1',
    cardId: 'mock-card-40',
    knowledgePointId: 'mock-kp-40',
    version: 1,
    title: '什么是最小可行产品？',
    conclusion: '最小可行产品用最少功能验证核心假设和用户价值。',
    explanation: 'MVP 不是低质量产品，而是控制范围后快速获得真实反馈的版本。',
    example: '先上线核心学习卡和复习功能，再验证用户是否愿意持续使用。',
    recallPrompt: 'MVP 的“最小”主要是减少什么？',
    referenceAnswer: '减少非核心范围，以更快验证核心价值。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 3 / Agile'
  },
  {
    id: 'mock-card-41-v1',
    cardId: 'mock-card-41',
    knowledgePointId: 'mock-kp-41',
    version: 1,
    title: '商业分析在项目中的作用是什么？',
    conclusion: '商业分析帮助识别业务需求，并把需求转化为可交付的解决方案。',
    explanation: '商业分析连接业务目标、相关方需求和项目交付结果。',
    example: '在开发功能前，先确认它要解决的用户问题和业务指标。',
    recallPrompt: '商业分析连接哪三类内容？',
    referenceAnswer: '业务目标、相关方需求和项目解决方案。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 4 / Business Analysis'
  },
  {
    id: 'mock-card-42-v1',
    cardId: 'mock-card-42',
    knowledgePointId: 'mock-kp-42',
    version: 1,
    title: '需求获取应该关注什么？',
    conclusion: '需求获取需要通过访谈、观察、研讨会等方式理解真实需要。',
    explanation: '用户提出的解决方案不一定等于真正需求，需要继续追问目标和场景。',
    example: '用户说需要一个报表，进一步了解后可能真正需要的是异常提醒。',
    recallPrompt: '需求获取时为什么不能只照抄用户提出的功能？',
    referenceAnswer: '功能请求背后可能还有未表达的业务目标和真实问题。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 4 / Business Analysis'
  },
  {
    id: 'mock-card-43-v1',
    cardId: 'mock-card-43',
    knowledgePointId: 'mock-kp-43',
    version: 1,
    title: '需求可追溯性是什么？',
    conclusion: '需求可追溯性记录需求与目标、交付物和验证结果之间的关系。',
    explanation: '追溯关系可以帮助团队确认每个需求都有来源、实现和验证依据。',
    example: '通过需求追踪矩阵可以查看一项需求对应的测试用例。',
    recallPrompt: '需求追踪能帮助发现哪些问题？',
    referenceAnswer: '遗漏需求、无来源需求和没有验证覆盖的需求。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 4 / Business Analysis'
  },
  {
    id: 'mock-card-44-v1',
    cardId: 'mock-card-44',
    knowledgePointId: 'mock-kp-44',
    version: 1,
    title: '需求确认和需求验证有什么区别？',
    conclusion: '确认关注需求是否被相关方接受，验证关注需求是否清晰、完整和可测试。',
    explanation: '需求既要符合业务目标，也要能被团队准确理解和实现。',
    example: '相关方同意需求不代表需求已经足够具体可测试。',
    recallPrompt: '一个被业务方接受的需求一定是可测试的吗？',
    referenceAnswer: '不一定，还需要检查清晰性、完整性和可测试性。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 4 / Business Analysis'
  },
  {
    id: 'mock-card-45-v1',
    cardId: 'mock-card-45',
    knowledgePointId: 'mock-kp-45',
    version: 1,
    title: '需求优先级如何确定？',
    conclusion: '需求优先级应综合考虑价值、风险、紧急程度和实现成本。',
    explanation: '优先级不是只由提出者的职位决定，需要依据透明的决策标准。',
    example: '高价值且风险高的需求可能需要优先验证。',
    recallPrompt: '排需求优先级时除了价值，还要考虑什么？',
    referenceAnswer: '风险、紧急程度、依赖关系和实现成本等因素。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 4 / Business Analysis'
  },
  {
    id: 'mock-card-46-v1',
    cardId: 'mock-card-46',
    knowledgePointId: 'mock-kp-46',
    version: 1,
    title: '什么是业务案例？',
    conclusion: '业务案例说明为什么要开展项目，以及预期成本、收益和风险。',
    explanation: '它帮助组织比较不同投资机会，并支持项目是否启动的决策。',
    example: '上线学习工具前，需要说明目标用户、预期收益和投入成本。',
    recallPrompt: '业务案例主要支持什么类型的决策？',
    referenceAnswer: '是否启动项目以及如何选择投资方案。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 4 / Business Analysis'
  },
  {
    id: 'mock-card-47-v1',
    cardId: 'mock-card-47',
    knowledgePointId: 'mock-kp-47',
    version: 1,
    title: '产品路线图是什么？',
    conclusion: '产品路线图展示产品方向、主要目标和计划演进。',
    explanation: '路线图提供较高层级的方向，不等同于固定不变的详细项目进度表。',
    example: '路线图可以展示先做学习流，再做题库和数据分析。',
    recallPrompt: '路线图是详细任务清单吗？',
    referenceAnswer: '不是，它是描述方向和重点的高层级计划。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 4 / Business Analysis'
  },
  {
    id: 'mock-card-48-v1',
    cardId: 'mock-card-48',
    knowledgePointId: 'mock-kp-48',
    version: 1,
    title: '相关方需求冲突时怎么办？',
    conclusion: '应澄清各方目标和约束，基于价值和事实协商解决。',
    explanation: '不能简单按照最先提出或职位最高的一方决定，需要记录决策依据。',
    example: '运营希望快速上线，合规团队要求增加审核步骤，团队需要共同评估风险。',
    recallPrompt: '需求冲突时第一步是直接投票，还是先澄清目标？',
    referenceAnswer: '先澄清各方目标、约束和影响，再协商决策。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 4 / Business Analysis'
  },
  {
    id: 'mock-card-49-v1',
    cardId: 'mock-card-49',
    knowledgePointId: 'mock-kp-49',
    version: 1,
    title: '需求变更应该如何处理？',
    conclusion: '需求变更需要评估影响、更新相关记录并取得适当批准。',
    explanation: '变更可能影响范围、进度、成本、价值和验收标准。',
    example: '新增支付方式前，需要确认对安全、测试和上线计划的影响。',
    recallPrompt: '需求变更最容易遗漏评估哪些方面？',
    referenceAnswer: '范围、进度、成本、风险、质量和验收影响。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 4 / Business Analysis'
  },
  {
    id: 'mock-card-50-v1',
    cardId: 'mock-card-50',
    knowledgePointId: 'mock-kp-50',
    version: 1,
    title: '如何判断需求已经准备好开发？',
    conclusion: '需求应足够清晰、可理解、可验证，并具备必要的依赖信息。',
    explanation: '准备好的需求能让团队理解目标、范围、验收方式和相关限制。',
    example: '只有“优化体验”而没有具体用户场景和验收条件的需求还不够准备好。',
    recallPrompt: '“优化体验”为什么通常还不能直接开发？',
    referenceAnswer: '目标、范围和验收条件不够明确，无法形成一致理解。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 4 / Business Analysis'
  },
  {
    id: 'mock-card-51-v1',
    cardId: 'mock-card-51',
    knowledgePointId: 'mock-kp-51',
    version: 1,
    title: '验收结果如何支持收益实现？',
    conclusion: '验收确认交付物满足要求，是后续投入使用和实现收益的基础。',
    explanation: '验收不仅检查功能是否完成，也应确认相关方认可交付结果。',
    example: '学习卡功能通过验收后，还需要观察用户是否真正持续复习。',
    recallPrompt: '验收通过是否等同于业务收益已经实现？',
    referenceAnswer: '不等同，验收是收益实现的基础，收益还需要持续观察。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 4 / Business Analysis'
  },
  {
    id: 'mock-card-52-v1',
    cardId: 'mock-card-52',
    knowledgePointId: 'mock-kp-52',
    version: 1,
    title: '业务目标应该如何转化为项目目标？',
    conclusion: '项目目标需要把业务方向转化为可衡量、可验证的结果。',
    explanation: '清晰的项目目标应说明要改变什么、为谁创造价值以及如何判断是否达成。',
    example: '“提升学习体验”可以转化为“提高复习完成率并降低首次学习阻力”。',
    recallPrompt: '为什么“提升体验”还不算完整的项目目标？',
    referenceAnswer: '因为缺少明确的结果、衡量方式和目标范围。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 4 / Business Analysis'
  },
  {
    id: 'mock-card-53-v1',
    cardId: 'mock-card-53',
    knowledgePointId: 'mock-kp-53',
    version: 1,
    title: '产品价值应该如何验证？',
    conclusion: '产品价值需要通过可观察的用户行为和业务结果验证。',
    explanation: '完成开发只是交付，使用率、满意度、效率或收益等结果才能说明价值是否实现。',
    example: '学习卡上线后，需要观察用户是否持续复习，而不只是统计上线数量。',
    recallPrompt: '为什么上线不等于实现价值？',
    referenceAnswer: '因为价值要通过用户使用和业务结果体现。',
    source: 'PMI CAPM ECO（Mock）',
    sourceLocator: 'Domain 4 / Business Analysis'
  }
]
